{% set name = "globus-compute-common" %}
{% set version = "0.4.1" %}

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/globus-compute-common-{{ version }}.tar.gz
    sha256: 212ec345e2ea4989ad56a6066a078ce756508f9ad30af87110d7308112aea30f
  - url: https://raw.githubusercontent.com/funcx-faas/funcx-common/main/LICENSE
    sha256: c71d239df91726fc519c6eb72d318ec65820627232b2f796219e87dcf35d0ab4

build:
  noarch: python
  number: 1

requirements:
  host:
    - python >=3.7

outputs:

  - name: globus-compute-common
    script: install.sh  # [unix]
    script: install.bat  # [win]
    build:
      noarch: python
    requirements:
      host:
        - python >=3.7
        - pip
      run:
        - python >=3.7
        - pydantic >=1,<3
    test:
      imports:
        - globus_compute_common
      commands:
        - pip check
      requires:
        - pip

  - name: globus-compute-common-moto
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage('globus-compute-common', exact=True) }}
        - moto <6
    test:
      imports:
        - globus_compute_common
      commands:
        - pip check
      requires:
        - pip

  - name: globus-compute-common-boto3
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage('globus-compute-common', exact=True) }}
        - boto3 >=1.19.0
    test:
      imports:
        - globus_compute_common
      commands:
        - pip check
      requires:
        - pip

  - name: globus-compute-common-redis
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage('globus-compute-common', exact=True) }}
        - redis-py >=3.5.3,<6
    test:
      imports:
        - globus_compute_common
      commands:
        - pip check
      requires:
        - pip

about:
  home: https://github.com/funcX-faas/funcx-common
  summary: Common tools for Globus Compute projects
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/globus-compute-sdk
    - WardLT
    - jan-janssen
